FROM php:8.0-fpm

RUN apt-get update \
    && apt-get install -y \
        wget \
        curl \
        nano \
        libcurl4-openssl-dev \
        libxml2-dev \
        zlib1g-dev \
        libpng-dev \
        libonig-dev \
        libzip-dev \
        libicu-dev

RUN apt-get install -y \
    && docker-php-ext-install curl \
    && docker-php-ext-install dom \
    && docker-php-ext-install gd \
    && docker-php-ext-install intl \
    && docker-php-ext-install mbstring \
    && docker-php-ext-install pdo \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install zip \
    && docker-php-ext-install bcmath \
    && docker-php-ext-install simplexml \
    && docker-php-ext-install opcache

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY configs/php/php.ini /usr/local/etc/php/

RUN rm -rf /etc/localtime \
        && ln -s /usr/share/zoneinfo/Europe/Madrid /etc/localtime

WORKDIR /var/www/html

# Enabled in Docker
COPY www/ .

EXPOSE 9000

CMD ["php-fpm"]
